name: Build and Test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main


jobs:

  macos-build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-12, macos-latest ]
        arch: [ x64, aarch64 ]
        include:
          - arch: x64
            jarch: x86_64
          - arch: aarch64
            jarch: aarch64
    steps:
      - name: Install Tools
        run: |
          brew install yasm
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
          architecture: x64

      # cache maven repo for faster builds
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build/test code with Maven
        run: mvn --activate-profiles compile,ffmpeg-${{ matrix.jarch }}-macos --batch-mode install --file pom.xml


  windows-build:

    runs-on: windows-2019
    strategy:
      matrix:
        arch: [ x64, x86 ]
        include:
          - arch: x64
            jarch: x86_64
            sys: mingw64
            env: x86_64
          - arch: x86
            jarch: i386
            sys: mingw32
            env: i686
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          install: mingw-w64-${{ matrix.env }}-toolchain
          path-type: inherit

      - name: Install Tools
        run: |
          pacman --noconfirm -S mingw-w64-${{ matrix.env }}-yasm

      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # cache maven repo for faster builds
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build/test code with Maven
        run: |
          which mvn
          mvn --activate-profiles compile,ffmpeg-${{ matrix.jarch }}-win --batch-mode install --file pom.xml


  linux-build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-latest ]
        arch: [ x64 ]
        include:
          - arch: x64
            jarch: x86_64

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # cache maven repo for faster builds
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build/test code with Maven
        run: mvn --activate-profiles compile,ffmpeg-${{ matrix.jarch }}-unix --batch-mode install --file pom.xml
